### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by trashcluster** [lyon-esport/AdminAFK#10]
Is there any support for Docker planned ?

**Comment by M0NsTeRRR** [comment]
Hello, thanks you for your feedback. I will work on it.
I will provide a Docker compose running with php-apache and Mysql, so you can use eBot or docker-eBot (as you prefer).
I will recommend to use a reverse proxy (to configure SSL or to make some port forwarding etc...) or to update the Docker compose for your use case.

**Comment by M0NsTeRRR** [comment]
Add Docker support in V1.80. I close the issue, if you have any bugs with Docker version open a new issue.
