### ISSUE TITLE
Broken link to licence CeCILL

### ISSUE THREAD

**Issue by ICPvser** [lyon-esport/AdminAFK#12]
Use https://cecill.info/licences/Licence_CeCILL_V2.1-en.html instead of https://www.cecill.info/licences/Licence_CeCILL_V2.1-en.html

into README.md

**Comment by M0NsTeRRR** [comment]
Thanks you for your feedback fixed in https://github.com/lyon-esport/AdminAFK/commit/0327fcbb5875d21a28382084d163ca5c92705379
