### ISSUE TITLE
Docker-compose.yml does not properly import variables into config/config.php

### ISSUE THREAD

**Issue by imjustafox** [lyon-esport/AdminAFK#13]
Figured this out, working on a fix currently.  Will update when fix is found.

**Comment by M0NsTeRRR** [comment]
Hello,

I've tried and environment variables are passed properly into the container but I get HTTP 500 error at the begginning (first 2mn i think) and after that it works well. Maybe adminafk is trying to connect to eBot or adminafk database before database are ready. When i've time I will try to look into in if you haven't fixed it before :)

Best regards,

**Comment by M0NsTeRRR** [comment]
I've fixed the default name of the container, can you provide me more informations about your problem because I can't reproduce it ?

Best regards,

**Comment by imjustafox** [comment]
Sure thing, I'll spin it up and do a proper write up, I may have been a bad sysadmin and been drinking while building things. I'll set a reminder and get on that tomorrow.
