### ISSUE TITLE
 question about adminafk.

### ISSUE THREAD

**Issue by mrc4tt** [lyon-esport/AdminAFK#14]
Hi,

Is it possible to make it possible for BO2 & BO3 can be used for choose "own map" without VETO with AdminAFK?

I have never figure to get adminafk work (because I use diff PHP versions): Php 5.6 (for eBot) and PHP 7.4 for AdminAFK,

Where it does show like (on screenshot):
![](https://pic.lindhost.eu/chrome_t5J7fHgvcR.png)

So I was thinking, about I can contact the author "private on Discord or some-where" :-)

**Comment by M0NsTeRRR** [comment]
Hello,

Map veto is an independant system, if you don't need it don't use it. Only duty map pool is available through setbo1 or setbo3 (maps are harcoded) but I can do for you a customized version to handle your custom map.

The latest PHP version supported is 7.0.24

My discord : -MoNsTeRRR#2160

Best regards,

**Comment by mrc4tt** [comment]
I did add you as mrc4t#2090 on discord.

I have some questions for you with AdminAFK, so I think it's better to ask on Discord. =D
